### ISSUE TITLE
Can provide example file or tutorial

### ISSUE THREAD

**Issue by hsiaoyi0504** [enanomapper/RRegrs#16]
Hello, I'm a reader of your paper published on the JCheminformatics
I want to try to use this library
Can you provide some tutorial or example file such as the applications presented in the paper?
I think it will be very useful to provide that and encourage beginners to use this tool
Thanks

**Comment by muntisa** [comment]
Please check:
- the tutorial from this repository: https://github.com/enanomapper/RRegrs/blob/master/RRegrs-package-tutorial.pdf
- examples of RRegrs() calls from page 14 from the publication: http://www.jcheminf.com/content/pdf/s13321-015-0094-2.pdf.
- one test script in this repository: https://github.com/enanomapper/RRegrs/blob/master/TEST/TestRRegrs.R

If you will read the publication about RRegrs you should understand you can use any dataset you want using the described format. You can see examples of datasets into this repository too: https://github.com/enanomapper/RRegrs/tree/master/TEST/ds.

Please install the last version of RRegrs! Check the last corrections!

Thanks for the interest!

**Comment by hsiaoyi0504** [comment]
Sorry, I don't note that there are a pdf in the homepage
Just a suggestion, add these resources to the README.md, which makes this project more friendly to users
Thanks!
