### ISSUE TITLE
RRegrs installation failed in Ubuntu 14.04

### ISSUE THREAD

**Issue by organiker127** [enanomapper/RRegrs#17]
library(devtools)
install_github("enomapper/RRegrs", subdir = "RRegrs") gave the following output:

Downloading GitHub repo enomapper/RRegrs@master
Error in download(dest, src, auth) : client error: (404) Not Found

Downloaded RRegrs-0.0.5.tar.gz into my home folder and ran in R 3.2.2 the following:

install.packages("RRegrs-0.0.5.tar.gz", repos = NULL, type = "source") gave:

Installing package into ‘/home/nathan/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from ‘RRegrs-0.0.5.tar.gz’
Warning in install.packages :
  installation of package ‘RRegrs-0.0.5.tar.gz’ had non-zero exit status

The alternative method of running R CMD routine also failed.

**Comment by cafernandezlo** [comment]
please check your URL, is wrong. Please copy-paste the following:

install_github("enanomapper/RRegrs", subdir="RRegrs")

**Comment by organiker127** [comment]
Thank you!  That worked, except that I had to re-install kerntools and invoke library(kerntools) as well as library(devtools).
