### ISSUE TITLE
Automatically create DataResults folder and copy dataset to it

### ISSUE THREAD

**Issue by miguelcorrea** [enanomapper/RRegrs#7]
As it is now, the user has to create a DataResults folder and copy the dataset to it by himself, which is not very user friendly. I suggest that this is done automatically when calling the RRegrs function.

**Comment by egonw** [comment]
@miguelcorrea can you please copy/paste the error message you get?

**Comment by egonw** [comment]
Never mind. BTW, there is no default data set. (Or not in the package, anyway)
